"""
ACQ Game Dataset - Mixed Fun Trivia Questions
Variety is key! Each question is different and interesting!
"""

quiz_dataset = [
    {
        "id": 1,
        "question": "What is the only food that never goes bad?",
        "choices": ["Rice", "Honey", "Salt", "Sugar"],
        "correct_answer": "Honey",
        "topic": "food",
        "subtopic": "facts",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Honey can last forever due to its low moisture and acidic properties!"
    },
    {
        "id": 2,
        "question": "Which planet is known for having a giant storm called the Great Red Spot?",
        "choices": ["Saturn", "Jupiter", "Mars", "Neptune"],
        "correct_answer": "Jupiter",
        "topic": "space",
        "subtopic": "planets",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Jupiter's Great Red Spot is a massive storm that's been raging for centuries!"
    },
    {
        "id": 3,
        "question": "What is a group of lions called?",
        "choices": ["Pack", "Herd", "Pride", "Flock"],
        "correct_answer": "Pride",
        "topic": "animals",
        "subtopic": "collective_nouns",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "A group of lions is called a pride!"
    },
    {
        "id": 4,
        "question": "In which country would you find the ancient city of Machu Picchu?",
        "choices": ["Mexico", "Peru", "Brazil", "Chile"],
        "correct_answer": "Peru",
        "topic": "geography",
        "subtopic": "landmarks",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Machu Picchu is an ancient Incan city located in Peru!"
    },
    {
        "id": 5,
        "question": "What does 'www' stand for in a website browser?",
        "choices": ["World Wide Web", "World Web Window", "Web World Wide", "Window Web World"],
        "correct_answer": "World Wide Web",
        "topic": "technology",
        "subtopic": "internet",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "WWW stands for World Wide Web!"
    },
    {
        "id": 6,
        "question": "Which soft drink was originally created as medicine?",
        "choices": ["Sprite", "Coca-Cola", "Fanta", "Pepsi"],
        "correct_answer": "Coca-Cola",
        "topic": "history",
        "subtopic": "inventions",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Coca-Cola was originally created in the 1880s as a medicinal tonic!"
    },
    {
        "id": 7,
        "question": "What animal is known to laugh when tickled?",
        "choices": ["Monkeys", "Dolphins", "Rats", "Dogs"],
        "correct_answer": "Rats",
        "topic": "animals",
        "subtopic": "behavior",
        "difficulty": "hard",
        "points": 30,
        "time_limit": 25,
        "explanation": "Scientists discovered that rats make high-pitched giggles when tickled!"
    },
    {
        "id": 8,
        "question": "How many hearts does an octopus have?",
        "choices": ["1", "2", "3", "4"],
        "correct_answer": "3",
        "topic": "nature",
        "subtopic": "marine_life",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Octopuses have three hearts - two pump blood to the gills, one to the body!"
    },
    {
        "id": 9,
        "question": "What popular video game character has to rescue Princess Peach?",
        "choices": ["Sonic", "Mario", "Link", "Donkey Kong"],
        "correct_answer": "Mario",
        "topic": "gaming",
        "subtopic": "characters",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Mario is always on a quest to rescue Princess Peach from Bowser!"
    },
    {
        "id": 10,
        "question": "What fruit was once so rare that people would rent it to show off at parties?",
        "choices": ["Mango", "Pineapple", "Coconut", "Papaya"],
        "correct_answer": "Pineapple",
        "topic": "history",
        "subtopic": "food_history",
        "difficulty": "hard",
        "points": 30,
        "time_limit": 25,
        "explanation": "In the 1700s, pineapples were so expensive that people would rent them as party decorations!"
    },
    {
        "id": 11,
        "question": "Which Disney movie features the song 'Let It Go'?",
        "choices": ["Tangled", "Frozen", "Moana", "Brave"],
        "correct_answer": "Frozen",
        "topic": "movies",
        "subtopic": "disney",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "'Let It Go' is the iconic song from Disney's Frozen!"
    },
    {
        "id": 12,
        "question": "What is the largest desert in the world?",
        "choices": ["Sahara", "Gobi", "Antarctica", "Arabian"],
        "correct_answer": "Antarctica",
        "topic": "geography",
        "subtopic": "physical_features",
        "difficulty": "hard",
        "points": 30,
        "time_limit": 25,
        "explanation": "Antarctica is technically the largest desert - deserts are defined by low precipitation!"
    },
    {
        "id": 13,
        "question": "How many bones does an adult human have?",
        "choices": ["186", "206", "226", "246"],
        "correct_answer": "206",
        "topic": "science",
        "subtopic": "human_body",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Adults have 206 bones, while babies are born with around 300 that fuse together!"
    },
    {
        "id": 14,
        "question": "What does a panda spend most of its day doing?",
        "choices": ["Sleeping", "Eating bamboo", "Playing", "Climbing"],
        "correct_answer": "Eating bamboo",
        "topic": "animals",
        "subtopic": "habits",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Pandas spend 12-16 hours a day eating bamboo!"
    },
    {
        "id": 15,
        "question": "Which country invented pizza?",
        "choices": ["France", "Italy", "Greece", "Spain"],
        "correct_answer": "Italy",
        "topic": "food",
        "subtopic": "origins",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Pizza originated in Italy, specifically in Naples!"
    },
    {
        "id": 16,
        "question": "What year did the Titanic sink?",
        "choices": ["1910", "1912", "1914", "1916"],
        "correct_answer": "1912",
        "topic": "history",
        "subtopic": "disasters",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "The Titanic sank on April 15, 1912 after hitting an iceberg!"
    },
    {
        "id": 17,
        "question": "Which planet is closest to the Sun?",
        "choices": ["Venus", "Mars", "Mercury", "Earth"],
        "correct_answer": "Mercury",
        "topic": "space",
        "subtopic": "solar_system",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Mercury is the closest planet to the Sun!"
    },
    {
        "id": 18,
        "question": "What is the fastest land animal?",
        "choices": ["Lion", "Cheetah", "Gazelle", "Greyhound"],
        "correct_answer": "Cheetah",
        "topic": "animals",
        "subtopic": "speed",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Cheetahs can run up to 70 mph - the fastest land animal!"
    },
    {
        "id": 19,
        "question": "What popular toy was accidentally invented while trying to create a rubber substitute?",
        "choices": ["Slinky", "Play-Doh", "Silly Putty", "Frisbee"],
        "correct_answer": "Silly Putty",
        "topic": "history",
        "subtopic": "inventions",
        "difficulty": "hard",
        "points": 30,
        "time_limit": 25,
        "explanation": "James Wright accidentally invented Silly Putty during World War II!"
    },
    {
        "id": 20,
        "question": "Which social media app is known for its bird logo?",
        "choices": ["Facebook", "Instagram", "Twitter", "TikTok"],
        "correct_answer": "Twitter",
        "topic": "technology",
        "subtopic": "social_media",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Twitter (now X) is famous for its blue bird logo!"
    },
    {
        "id": 21,
        "question": "What is the largest mammal in the world?",
        "choices": ["African Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        "correct_answer": "Blue Whale",
        "topic": "animals",
        "subtopic": "size",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Blue whales can grow up to 100 feet long - the largest animal ever!"
    },
    {
        "id": 22,
        "question": "How many players are on a basketball team on the court?",
        "choices": ["4", "5", "6", "7"],
        "correct_answer": "5",
        "topic": "sports",
        "subtopic": "basketball",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Each basketball team has 5 players on the court at a time!"
    },
    {
        "id": 23,
        "question": "What is the smallest country in the world?",
        "choices": ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
        "correct_answer": "Vatican City",
        "topic": "geography",
        "subtopic": "countries",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Vatican City is only 0.17 square miles - the world's smallest country!"
    },
    {
        "id": 24,
        "question": "What Netflix show features a group of kids fighting monsters in Hawkins, Indiana?",
        "choices": ["The Witcher", "Stranger Things", "Wednesday", "Umbrella Academy"],
        "correct_answer": "Stranger Things",
        "topic": "tv_shows",
        "subtopic": "streaming",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Stranger Things is set in the fictional town of Hawkins!"
    },
    {
        "id": 25,
        "question": "What is the chemical symbol for gold?",
        "choices": ["Go", "Gd", "Au", "Ag"],
        "correct_answer": "Au",
        "topic": "science",
        "subtopic": "chemistry",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Au comes from the Latin word 'aurum' meaning gold!"
    },
    {
        "id": 26,
        "question": "Which animal never sleeps?",
        "choices": ["Shark", "Bullfrog", "Dolphin", "Horse"],
        "correct_answer": "Bullfrog",
        "topic": "animals",
        "subtopic": "sleep",
        "difficulty": "hard",
        "points": 30,
        "time_limit": 25,
        "explanation": "Bullfrogs are one of the few animals that never sleep!"
    },
    {
        "id": 27,
        "question": "What does a thermometer measure?",
        "choices": ["Pressure", "Temperature", "Humidity", "Speed"],
        "correct_answer": "Temperature",
        "topic": "science",
        "subtopic": "instruments",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "A thermometer measures temperature!"
    },
    {
        "id": 28,
        "question": "In which city would you find the Eiffel Tower?",
        "choices": ["London", "Rome", "Paris", "Berlin"],
        "correct_answer": "Paris",
        "topic": "geography",
        "subtopic": "landmarks",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "The Eiffel Tower is located in Paris, France!"
    },
    {
        "id": 29,
        "question": "What gaming console is made by Sony?",
        "choices": ["Xbox", "Nintendo Switch", "PlayStation", "Steam Deck"],
        "correct_answer": "PlayStation",
        "topic": "gaming",
        "subtopic": "consoles",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Sony makes the PlayStation gaming console!"
    },
    {
        "id": 30,
        "question": "What do you call a baby kangaroo?",
        "choices": ["Cub", "Pup", "Joey", "Kit"],
        "correct_answer": "Joey",
        "topic": "animals",
        "subtopic": "baby_names",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Baby kangaroos are called joeys!"
    },
    {
        "id": 31,
        "question": "Which superhero is known as the 'Dark Knight'?",
        "choices": ["Superman", "Batman", "Iron Man", "Spider-Man"],
        "correct_answer": "Batman",
        "topic": "movies",
        "subtopic": "superheroes",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Batman is often called the Dark Knight!"
    },
    {
        "id": 32,
        "question": "How many sides does a hexagon have?",
        "choices": ["5", "6", "7", "8"],
        "correct_answer": "6",
        "topic": "math",
        "subtopic": "shapes",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "A hexagon has 6 sides!"
    },
    {
        "id": 33,
        "question": "What is the tallest mountain in the world?",
        "choices": ["K2", "Kilimanjaro", "Mount Everest", "Denali"],
        "correct_answer": "Mount Everest",
        "topic": "geography",
        "subtopic": "mountains",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Mount Everest is 29,032 feet tall - the world's tallest mountain!"
    },
    {
        "id": 34,
        "question": "What is the main ingredient in hummus?",
        "choices": ["Lentils", "Chickpeas", "Beans", "Peas"],
        "correct_answer": "Chickpeas",
        "topic": "food",
        "subtopic": "ingredients",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Hummus is made primarily from chickpeas!"
    },
    {
        "id": 35,
        "question": "What year did humans first land on the Moon?",
        "choices": ["1965", "1967", "1969", "1971"],
        "correct_answer": "1969",
        "topic": "space",
        "subtopic": "exploration",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Neil Armstrong landed on the Moon on July 20, 1969!"
    },
    {
        "id": 36,
        "question": "Which sea creature has three hearts and blue blood?",
        "choices": ["Jellyfish", "Octopus", "Squid", "Starfish"],
        "correct_answer": "Octopus",
        "topic": "animals",
        "subtopic": "marine_biology",
        "difficulty": "hard",
        "points": 30,
        "time_limit": 25,
        "explanation": "Octopuses have three hearts and copper-based blue blood!"
    },
    {
        "id": 37,
        "question": "What sport is played at Wimbledon?",
        "choices": ["Golf", "Tennis", "Cricket", "Soccer"],
        "correct_answer": "Tennis",
        "topic": "sports",
        "subtopic": "tournaments",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Wimbledon is the oldest tennis tournament in the world!"
    },
    {
        "id": 38,
        "question": "What does 'HTTP' stand for?",
        "choices": ["HyperText Transfer Protocol", "High Transfer Text Protocol", "HyperText Transmission Process", "Home Tool Transfer Protocol"],
        "correct_answer": "HyperText Transfer Protocol",
        "topic": "technology",
        "subtopic": "internet",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "HTTP stands for HyperText Transfer Protocol!"
    },
    {
        "id": 39,
        "question": "Which bird can fly backwards?",
        "choices": ["Eagle", "Hummingbird", "Parrot", "Owl"],
        "correct_answer": "Hummingbird",
        "topic": "animals",
        "subtopic": "birds",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Hummingbirds are the only birds that can fly backwards!"
    },
    {
        "id": 40,
        "question": "What is the capital of Japan?",
        "choices": ["Osaka", "Kyoto", "Tokyo", "Hiroshima"],
        "correct_answer": "Tokyo",
        "topic": "geography",
        "subtopic": "capitals",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Tokyo is the capital city of Japan!"
    },
    {
        "id": 41,
        "question": "In what game do you say 'checkmate'?",
        "choices": ["Checkers", "Chess", "Monopoly", "Poker"],
        "correct_answer": "Chess",
        "topic": "gaming",
        "subtopic": "board_games",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "'Checkmate' is the winning move in chess!"
    },
    {
        "id": 42,
        "question": "What is the longest river in the world?",
        "choices": ["Amazon", "Nile", "Yangtze", "Mississippi"],
        "correct_answer": "Nile",
        "topic": "geography",
        "subtopic": "rivers",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "The Nile River is approximately 6,650 km long!"
    },
    {
        "id": 43,
        "question": "What popular video app is known for short dance videos?",
        "choices": ["YouTube", "TikTok", "Instagram", "Snapchat"],
        "correct_answer": "TikTok",
        "topic": "technology",
        "subtopic": "social_media",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "TikTok is famous for its short-form dance and comedy videos!"
    },
    {
        "id": 44,
        "question": "What is the hardest natural substance on Earth?",
        "choices": ["Steel", "Diamond", "Titanium", "Granite"],
        "correct_answer": "Diamond",
        "topic": "science",
        "subtopic": "materials",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Diamonds are the hardest naturally occurring substance!"
    },
    {
        "id": 45,
        "question": "Which animal can change its color to match its surroundings?",
        "choices": ["Gecko", "Chameleon", "Frog", "Lizard"],
        "correct_answer": "Chameleon",
        "topic": "animals",
        "subtopic": "camouflage",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Chameleons can change color for camouflage and communication!"
    },
    {
        "id": 46,
        "question": "What is the name of the fairy in Peter Pan?",
        "choices": ["Cinderella", "Tinker Bell", "Ariel", "Belle"],
        "correct_answer": "Tinker Bell",
        "topic": "movies",
        "subtopic": "disney",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Tinker Bell is Peter Pan's fairy companion!"
    },
    {
        "id": 47,
        "question": "How many colors are in a rainbow?",
        "choices": ["5", "6", "7", "8"],
        "correct_answer": "7",
        "topic": "science",
        "subtopic": "nature",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Rainbows have 7 colors: red, orange, yellow, green, blue, indigo, violet!"
    },
    {
        "id": 48,
        "question": "What fruit is known for having its seeds on the outside?",
        "choices": ["Apple", "Strawberry", "Banana", "Orange"],
        "correct_answer": "Strawberry",
        "topic": "food",
        "subtopic": "fruits",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Strawberries are unique because their seeds are on the outside!"
    },
    {
        "id": 49,
        "question": "Which planet has the most moons?",
        "choices": ["Earth", "Mars", "Jupiter", "Saturn"],
        "correct_answer": "Saturn",
        "topic": "space",
        "subtopic": "moons",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Saturn has over 140 known moons - the most in our solar system!"
    },
    {
        "id": 50,
        "question": "What do you call a scientist who studies rocks?",
        "choices": ["Biologist", "Geologist", "Astronomer", "Meteorologist"],
        "correct_answer": "Geologist",
        "topic": "science",
        "subtopic": "careers",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Geologists study rocks, minerals, and the Earth's structure!"
    },
    {
        "id": 51,
        "question": "What animal is known as the 'ship of the desert'?",
        "choices": ["Horse", "Elephant", "Camel", "Donkey"],
        "correct_answer": "Camel",
        "topic": "animals",
        "subtopic": "nicknames",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Camels are called 'ships of the desert' because they can travel long distances!"
    },
    {
        "id": 52,
        "question": "Which ocean is the largest?",
        "choices": ["Atlantic", "Indian", "Arctic", "Pacific"],
        "correct_answer": "Pacific",
        "topic": "geography",
        "subtopic": "oceans",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "The Pacific Ocean covers about 46% of Earth's water surface!"
    },
    {
        "id": 53,
        "question": "What is the name of Harry Potter's owl?",
        "choices": ["Scabbers", "Hedwig", "Crookshanks", "Fawkes"],
        "correct_answer": "Hedwig",
        "topic": "movies",
        "subtopic": "harry_potter",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Hedwig is Harry's loyal snowy owl!"
    },
    {
        "id": 54,
        "question": "What is the boiling point of water?",
        "choices": ["90°C", "95°C", "100°C", "105°C"],
        "correct_answer": "100°C",
        "topic": "science",
        "subtopic": "temperature",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Water boils at 100°C (212°F) at sea level!"
    },
    {
        "id": 55,
        "question": "Which app's logo is a ghost?",
        "choices": ["Instagram", "Snapchat", "WhatsApp", "Messenger"],
        "correct_answer": "Snapchat",
        "topic": "technology",
        "subtopic": "apps",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "Snapchat's logo is a friendly ghost named Ghostface Chillah!"
    },
    {
        "id": 56,
        "question": "What is the largest organ in the human body?",
        "choices": ["Heart", "Brain", "Liver", "Skin"],
        "correct_answer": "Skin",
        "topic": "science",
        "subtopic": "human_body",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Skin is the largest organ, covering about 20 square feet!"
    },
    {
        "id": 57,
        "question": "Which continent is the driest?",
        "choices": ["Africa", "Australia", "Antarctica", "Asia"],
        "correct_answer": "Antarctica",
        "topic": "geography",
        "subtopic": "continents",
        "difficulty": "hard",
        "points": 30,
        "time_limit": 25,
        "explanation": "Antarctica is the driest continent - it's technically a desert!"
    },
    {
        "id": 58,
        "question": "What do bees make?",
        "choices": ["Silk", "Honey", "Wax", "Both honey and wax"],
        "correct_answer": "Both honey and wax",
        "topic": "animals",
        "subtopic": "insects",
        "difficulty": "medium",
        "points": 20,
        "time_limit": 20,
        "explanation": "Bees produce both honey (for food) and beeswax (for their hives)!"
    },
    {
        "id": 59,
        "question": "What is the name of the longest wall in the world?",
        "choices": ["Berlin Wall", "Great Wall of China", "Hadrian's Wall", "Western Wall"],
        "correct_answer": "Great Wall of China",
        "topic": "history",
        "subtopic": "structures",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "The Great Wall of China is over 13,000 miles long!"
    },
    {
        "id": 60,
        "question": "What does 'LOL' stand for?",
        "choices": ["Lots of Love", "Laugh Out Loud", "Living Online", "Lots of Laughs"],
        "correct_answer": "Laugh Out Loud",
        "topic": "technology",
        "subtopic": "internet_slang",
        "difficulty": "easy",
        "points": 10,
        "time_limit": 15,
        "explanation": "LOL means 'Laugh Out Loud' - used when something is funny!"
    }
]
